<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_ServerOpcUa" Id="{e7b0a92e-6673-4460-843f-494f972b71f9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ServerOpcUa
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ServerOpcUa">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>